# https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/schema
project:
  type: website
  output-dir: docs
  preview:
    browser: true
    watch-inputs: true
    navigate: true
    timeout: 300

website:
  title: "Hello, ADaM"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resources.qmd
        text: Resources
    right:
      - icon: github
        href: https://github.com/chizapoth/hello-adam
  open-graph: true
  search:
    type: overlay
    copy-button: true

format:
  html:
    grid:
      body-width: 1000px
    css: styles.css
    toc: true
    theme:
      light:
        - flatly
      dark:
        - darkly
    anchor-sections: true
    smooth-scroll: true

execute:
  freeze: false
  cache: false
  code-line-numbers: true
  eval: true

editor:
  mode: source

highlight-style: github
